-keepattributes *Annotation*, InnerClasses, Signature
-dontnote kotlinx.serialization.**
-keepclassmembers class kotlinx.serialization.json.** { *** Companion; }
-keepclasseswithmembers class **$$serializer { *; }
-keep,includedescriptorclasses class com.technewz.app.**$$serializer { *; }
-keepclassmembers class com.technewz.app.** { *** Companion; kotlinx.serialization.KSerializer serializer(...); }
-dontwarn org.jspecify.**
-dontwarn com.google.re2j.**
-dontwarn okhttp3.internal.platform.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
